### ISSUE TITLE
Docker images v7.0.x unable to login when using GitLab OAuth2.

### ISSUE THREAD

**Issue by hoo-richard** [alerta/docker-alerta#124]
Both v7.0.0 & v7.0.1 dockers will give this error upon login using GitLab OAuth2 :
Error: Expecting value: line 1 column 1 (char 0)

Rollback to v6.8.5 and able to login normally without any errors.

**Comment by satterly** [comment]
Did you hard refresh your browser before trying to login? The web UI's are completely different and there's no way it would work otherwise.

If the problem persists, please fill in the full bug report template that you would have seen when filing this issue originally so that I have enough information to reproduce the problem. Thanks.

**Issue Summary**
A clear and concise description of what the bug is.

**Environment**
- OS: [eg. Linux, Mac, Windows]
- API version: [eg. 6.8.1]
- Deployment: [eg. Docker, Heroku, AWS, GCloud, self-hosted]
- For self-hosted, WSGI environment: [eg. nginx/uwsgi, apache/mod_wsgi]

- Database: [eg. MongoDB, Postgres]

- Server config:
  Auth enabled? Yes/No
  Auth provider? Google, GitHub, OpenID, Basic, LDAP, etc
  Customer views? Yes/No
  (or provide the `/config` endpoint output)

- web UI version: [eg. 6.8.1]
- CLI version: [eg. 6.8.1]

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....' or Run '...'
3. Scroll down to '....'
4. See error (include command output)

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.


NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by hoo-richard** [comment]
Yes, I did a Ctrl+F5 hard refresh before reporting this.

**Issue Summary**
A clear and concise description of what the bug is.

**Environment**
- OS: Ubuntu 16.04 LTS
- API version: [eg. 6.8.1]
- Deployment: Docker [image: alerta/alerta-web]
- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? GitLab
  Customer views? Yes/No
  (or provide the `/config` endpoint output)

- web UI version: 7.0.0 & 7.0.1

**To Reproduce**
Steps to reproduce the behavior:
1. Start docker-compose up -d
2. Click on 'LOG IN'
3. A pop up GitLab window will appear and close immediate. (since already Authorized)
4. Then the message "Error: Expecting value: line 1 column 1 (char 0)", and not able to login. (see screenshot below)

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**
Clicking "LOG IN" will enter the dashboard web UI as usual.

**Screenshots**
![image](https://user-images.githubusercontent.com/34022006/56552025-8324e100-65bc-11e9-9cd8-b216e24a1326.png)

**Comment by satterly** [comment]
I've upgraded from v6.8.5 to v7.0.1 repeatedly to try to reproduce this error and can't.

That error usually means the web UI is expecting a JSON response but it is getting HTML back from the server. And this usually only happens if the endpoint URL is wrong. But if it working for v6.8.5 then I don't know why that should be.

You'll need to open the web browser developer console and check the JavaScript console tab for the error to see if there's any more detail and the Network tab for the exact HTTP request that is causing the error. Look for something with an HTML response instead of JSON.

**Comment by hoo-richard** [comment]
The console tab did log any error when the screenshot above showed up.

However, doing a F5 refresh on the redirected URL :
https://domain.com/login?redirect=%2Falerts
shows the error below.

"The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol."

![image](https://user-images.githubusercontent.com/34022006/56564680-343d7280-65e1-11e9-988a-0b349b1835f5.png)


On the Network tab the response is JSON with this payload :
{"code":500,"errors":["Traceback (most recent call last):\n  File \"/venv/lib/python3.6/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/venv/lib/python3.6/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/venv/lib/python3.6/site-packages/flask_cors/decorator.py\", line 128, in wrapped_function\n    resp = make_response(f(*args, **kwargs))\n  File \"/venv/lib/python3.6/site-packages/alerta/auth/oidc.py\", line 53, in openid\n    oidc_configuration, jwt_key_set = get_oidc_configuration(current_app)\n  File \"/venv/lib/python3.6/site-packages/alerta/auth/oidc.py\", line 33, in get_oidc_configuration\n    config = r.json()\n  File \"/venv/lib/python3.6/site-packages/requests/models.py\", line 897, in json\n    return complexjson.loads(self.text, **kwargs)\n  File \"/usr/local/lib/python3.6/json/__init__.py\", line 354, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/local/lib/python3.6/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/local/lib/python3.6/json/decoder.py\", line 357, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n"],"message":"Expecting value: line 1 column 1 (char 0)","status":"error"}

![image](https://user-images.githubusercontent.com/34022006/56564949-c0e83080-65e1-11e9-903c-d9ef9167c3da.png)

**Comment by satterly** [comment]
All OpenID Connect compliant auth providers (such as GitLab) use the same backend auth flow for Alerta now. This standard OIDC auth flow relies on the auth providers supplying a list of all required auth endpoints at a "well known" location. For GitLab it is at https://gitlab.com/.well-known/openid-configuration . Please ensure that your private hosted GitLab responds with similar information at the related endpoint. I suspect it isn't.

**Comment by hoo-richard** [comment]
That endpoint "/.well-known/openid-configuration" was not exposed on my private GitLab instance.

So, once I exposed it, I got a different error message :
Error: null value in column "email" violates not-null constraint DETAIL: Failing row contains (2, Richard Hoo, null, , active, {user}, {}, 2019-04-23 09:24:46.413, null, , 2019-04-23 09:24:46.413, f, null, hoo.richard). 

![image](https://user-images.githubusercontent.com/34022006/56570131-ef1f3d80-65ec-11e9-9fc2-74e710b84d4c.png)

**Comment by satterly** [comment]
Do you have an email address associated with your gitlab account?

**Comment by hoo-richard** [comment]
Yes, I do.
I can login my private GitLab instance using either my short username or full email address.

**Comment by satterly** [comment]
Have you only enabled "openid" and not "email" and "profile" also, as below?

<img width="661" alt="Screenshot 2019-04-23 at 11 37 47" src="https://user-images.githubusercontent.com/615057/56570998-4d7ff800-65bc-11e9-8b45-a778563d53a1.png">

**Comment by hoo-richard** [comment]
I only enabled openid checkbox, nothing else.

**Comment by satterly** [comment]
What happens if you enable "email"?

**Comment by hoo-richard** [comment]
No difference, got the same error even after enabling the email checkbox, or enabling profile checkbox together with it too.

**Comment by satterly** [comment]
The email address needs to be in the `id_token` returned in the token response or available from the `/userinfo` endpoint. Can you check that the OpenID configuration is including the email in either of these responses?
```
    email = userinfo.get('email') or id_token.get('email')
```

**Comment by satterly** [comment]
If you can't be bothered working out why your GitLab isn't passing through the email address then you can wait until tomorrow and I'll have deployed change to make email address no longer mandatory.

**Comment by hoo-richard** [comment]
Thank you.
Issue resolved with the latest docker image alerta/alerta-web:7.1.0
