### ISSUE TITLE
The resolved alarm message still exists in the Alerta UI

### ISSUE THREAD

**Issue by kerven88** [alerta/docker-alerta#155]
Will an alarm generated will not be deleted in the alerta UI after resolved?

I tested an alarm for node_exporter service down，when this alert resolved，The alarm status is still "Open"  in the alerta UI。
![2323](https://user-images.githubusercontent.com/51351006/63399671-d9d3e780-c403-11e9-87db-c5ea66c5a523.png)

**Comment by satterly** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information.

This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Gitter chat](https://gitter.im/alerta/chat).
