### ISSUE TITLE
Wrong config.json path while using Alerta behind Nginx proxy

### ISSUE THREAD

**Issue by feanorknd** [alerta/docker-alerta#161]
Hello,

I have used docker alerta image.
I am using BASE_URL fixed to /alerta/api.

Everything, fonts, js, css is loading correctly while using this NGINX configuration at reverse proxy:

>        location /alerta {
>                # Some auth
>                #auth_basic "Please AUTH";
>                #auth_basic_user_file auth/auth;
>
>                proxy_pass http://127.0.0.1:8080/alerta;
>        }

But I have seen <domain>/alerta web is looking for config.json file at <domain>/config.json instead of trying to get it from /alerta/config.json.

This is because of generated nginx.conf inside docker container for Alerta:

>                location /alerta/ {
>                        alias /web/;
>                        try_files $uri $uri/ /index.html;
>                }
>                location ~ config\.json$ {
>                        alias /web;
>                        try_files /config.json =404;
>                }
>                location /alerta/api {
>                        include /etc/nginx/uwsgi_params;
>                        uwsgi_pass unix:/tmp/uwsgi.sock;
>                        proxy_set_header Host $host:$server_port;
>                        proxy_set_header X-Real-IP $remote_addr;
>                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>                }

So If I want to use a Nginx reverse proxy as SSL termination point for Alerta, I need to define an extra location for /config.json at the main domain, as Alerta code is not using current /alerta/ path to get config.json file.

I think it would be a great idea to include config.json file inside path defined by BASE_URL env variable, IMHO.

Regards, and thanks so much!

**Comment by feanorknd** [comment]
Also noticed some /js/ and /css/ are requested on main domain without prefix/path when clicking menu options... :(

**Comment by PickingUpPieces** [comment]
@satterly Just a quick follow up since i have exact the same problem :( When i set the BASE_URL=/alerta/api then all alerta finds everything besides of the config.json. Without the BASE_URL set, but the endpoint to /alerta/api alerta finds the config.json but nothing else. Is there a fix for this? :) Thanks very much in advance

**Comment by satterly** [comment]
The fix is to build your own container with the `BASE_URL` set to the subpath you want. Support for setting the `BASE_URL` as a config option for the official Alerta docker container has been removed.

See https://github.com/alerta/docker-alerta/issues/177#issuecomment-533926324 for example of how to set `BASE_URL` during container build.

**Comment by satterly** [comment]
There is now a full working example of how to reverse proxy Alerta on a sub-path using nginx. See https://github.com/alerta/docker-alerta/tree/master/examples/nginx
