### ISSUE TITLE
doubt about the project.

### ISSUE THREAD

**Issue by LaurianoElmiroDuarte** [alerta/docker-alerta#212]
I installed the docker alert, I would like to know if the installation is complete.

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Gitter chat](https://gitter.im/alerta/chat).

**Comment by LaurianoElmiroDuarte** [comment]
@satterly thanks for listening .

**Comment by satterly** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
