### ISSUE TITLE
container is getting exited as soon as it is up

### ISSUE THREAD

**Issue by csomnath** [alerta/docker-alerta#26]
as soon as I run the following command : docker run --name alerta-web --link alerta-db:mongo -d -p 80:80 alerta/alerta-web
I see container is in exited status like below.
[root@master docker-alerta]# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
579634042fd3        alerta/alerta-web   "/docker-entrypoin..."   5 seconds ago       Exited (1) 4 seconds ago                       alerta-web
b19bf630f240        mongo               "docker-entrypoint..."   39 minutes ago      Up 39 minutes              27017/tcp           alerta-db

What can be the fix for this ?

**Comment by Ducatii** [comment]
I have the same problem as well.    Here's the log when with "docker logs CONTAINER_ID"

`MongoDB shell version: 2.6.10
connecting to: test
2017-06-14T18:32:42.239+0000 warning: Failed to connect to 127.0.0.1:27017, reason: errno:111 Connection refused
2017-06-14T18:32:42.240+0000 Error: couldn't connect to server 127.0.0.1:27017 (127.0.0.1), connection attempt failed at src/mongo/shell/mongo.js:146
exception: connect failed
`

I'm running Ubuntu 17.04 Zesty.

**Comment by satterly** [comment]
The problem here is that the `docker-entrypoint.sh` script was looking for a `MONGO_URI` environment variable which doesn't automatically exist when linking (as opposed to using the example [docker-compose.yml](https://github.com/alerta/docker-alerta/blob/master/docker-compose.yml) file) so you need to define it on the command line like this ...

```bash
$ export MONGO_URI=mongodb://db:27017/monitoring
$ docker run --name alerta-web -e MONGO_URI=$MONGO_URI --link alerta-db:db \
-d -p <port>:80 alerta/alerta-web
```

I've updated the README to reflect this in #27
